################################################################################
# [ 개발 서버 프로파일 ]
################################################################################

################################################################################
# Spring settings
spring:
  redis:
    host: cloud-redis.redis
    password: redis
    port: 6379
    sentinel:
      password: redis
      master: mymaster
      nodes: cloud-redis.redis:26379


################################################################################    
# Log properties   
logging:
  level:   
    org:
      apache: info

################################################################################
# swagger
springdoc:
  api-docs:
    enabled: true