################################################################################
# [ 로컬 서버 프로파일 ]
################################################################################

################################################################################
# Server Config
server:
  port: 7780

################################################################################
# Spring settings
spring:
  redis:
    host: 127.0.0.1
    port: 6379

################################################################################    
# Log properties   
logging:
  level:   
    org:
      apache: info

################################################################################
# swagger
springdoc:
  api-docs:
    enabled: true